sudo: required
dist: trusty
language: ruby
rvm:
  - 2.6.5

gemfile:
  - project/cucumber/Gemfile

before_install:
  - gem install ffi -f
  - gem install rspec-expectations
  - gem install bundler:2.1.4

addons:
  chrome: stable

before_script:
  - LATEST_CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE"`
  - curl "https://chromedriver.storage.googleapis.com/${LATEST_CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O
  - unzip chromedriver_linux64.zip -d ~/bin

script:
  - cucumber features
  - cucumber --format html --out reports/reports.html
