dist: trusty
language: ruby
rvm:
  - 2.6.5

gemfile:
  - Gemfile

before_install:
  - gem install ffi -f
  - gem install rspec-expectations

script:
  - cd project
  - cd cucumber
  - cucumber features
  - cucumber --format html --out reports/reports.html
