sudo: required
dist: trusty
language: ruby
rvm:
  - 2.6.5

gemfile:
  - project/cucumber/Gemfile

before_install:
  - gem install ffi -f
  - gem install rspec-expectations
  - gem install bundler:2.1.4

before_script:
  - CHROME_MAIN_VERSION=`google-chrome-stable --version | sed -E 's/(^Google Chrome |\.[0-9]+ )//g'`
  - CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_MAIN_VERSION"`
  - curl "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O
  - unzip chromedriver_linux64.zip -d ~/bin

script:
  - cucumber features
  - cucumber --format html --out reports/reports.html
